### ISSUE TITLE
Demo failure: NonType object has no attribute 'clear'

### ISSUE THREAD

**Issue by lanedsmu** [scales-okn/PACER-tools#8]
We're trying to set this up, and we're running into the following error when trying to run the demo

```
######
## Query Scraper Sequence [psc]
######

STARTING: Log file for scraper started at 2022-09-08-16:32:27
Initiated Query Scraper
Traceback (most recent call last):
  File "C:\git\PACER-tools\code\downloader\forms.py", line 29, in fill
    el.clear()
AttributeError: 'NoneType' object has no attribute 'clear'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 1772, in <module>
    main()
  File "C:\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 1721, in main
    query_results = seq_query(core_args, config, query_prefix)
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 1216, in seq_query
    results = QS.pull_queries()
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 337, in pull_queries
    login_success = self.launch_browser()
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 186, in launch_browser
    return self.login()
  File "C:\git\PACER-tools\code\downloader\scrapers.py", line 194, in login
    return stools.login(self.browser, self.auth, login_url, logging=logging)
  File "C:\git\PACER-tools\code\downloader\scraper_tools.py", line 105, in login
    login_form.fill()
  File "C:\git\PACER-tools\code\downloader\forms.py", line 105, in fill
    field.fill()
  File "C:\git\PACER-tools\code\downloader\forms.py", line 33, in fill
    el.clear()
AttributeError: 'NoneType' object has no attribute 'clear'
```

We're running Python 3.9.5, with:
```
Package                  Version
------------------------ -----------
agate                    1.6.3
async-generator          1.10
attrs                    22.1.0
azure-core               1.25.0
azure-identity           1.10.0
Babel                    2.10.3
beautifulsoup4           4.11.1
bs4                      0.0.1
certifi                  2022.6.15
cffi                     1.15.1
charset-normalizer       2.1.0
click                    8.0.3
colorama                 0.4.4
cryptography             37.0.4
dbt-core                 1.0.8
dbt-extractor            0.4.1
dbt-mysql                1.0.0
dbt-sqlserver            1.1.0
filelock                 3.8.0
future                   0.18.2
ghp-import               2.0.2
h11                      0.13.0
hologram                 0.0.14
idna                     3.3
importlib-metadata       4.11.1
isodate                  0.6.1
Jinja2                   2.11.3
jsonschema               3.1.1
leather                  0.3.4
Logbook                  1.5.3
Markdown                 3.3.6
MarkupSafe               2.0.1
mashumaro                2.9
mergedeep                1.3.4
minimal-snowplow-tracker 0.0.2
mkdocs                   1.2.3
msal                     1.18.0
msal-extensions          1.0.0
msgpack                  1.0.4
mysql-connector-python   8.0.30
networkx                 2.8
numpy                    1.23.2
outcome                  1.2.0
packaging                21.3
pandas                   1.4.4
parsedatetime            2.4
pip                      22.2.2
portalocker              2.5.1
probableparsing          0.0.1
protobuf                 3.20.1
pycodestyle              2.8.0
pycparser                2.21
PyJWT                    2.4.0
pyodbc                   4.0.34
pyOpenSSL                22.0.0
pyparsing                3.0.7
pyrsistent               0.18.1
PySocks                  1.7.1
python-crfsuite          0.9.8
python-dateutil          2.8.2
python-slugify           6.1.2
pytimeparse              1.1.8
pytz                     2022.2.1
pywin32                  304
PyYAML                   6.0
pyyaml_env_tag           0.1
requests                 2.28.1
requests-file            1.5.1
scipy                    1.9.1
selenium                 4.2.0
selenium-requests        2.0.0
setuptools               56.0.0
six                      1.16.0
sniffio                  1.3.0
sortedcontainers         2.4.0
soupsieve                2.3.2.post1
sqlparse                 0.4.2
text-unidecode           1.3
tldextract               3.3.1
toml                     0.10.2
tqdm                     4.64.1
trio                     0.21.0
trio-websocket           0.9.2
typing-extensions        3.10.0.2
urllib3                  1.26.11
usaddress                0.5.10
watchdog                 2.1.6
Werkzeug                 2.1.2
wsproto                  1.2.0
xmltodict                0.13.0
zipp                     3.7.0
```

**Comment by scottgdaniel** [comment]
Hello Lane,

Thanks for pointing out this issue as well! It seems like PACER changed the way their demo site login works, and a new redirect was happening that confused the scraper. The issue should be fixed now; let me know if you're able to get the demo to work!

All best,
Scott
